// Code generated by command: go run lines.go -out internal/simd/asm_lines_amd64.s. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func lineMaskAVX2Asm(data []byte) (mask uint32, processed int)
// Requires: AVX, AVX2, SSE2
TEXT ·lineMaskAVX2Asm(SB), NOSPLIT, $0-40
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	CMPQ         CX, $0x00000020
	JB           line_mask_done
	MOVL         $0x0000000a, CX
	MOVD         CX, X0
	VPBROADCASTB X0, Y0
	MOVL         $0x0000000d, CX
	MOVD         CX, X1
	VPBROADCASTB X1, Y1
	VMOVDQU      (AX), Y2
	VPCMPEQB     Y0, Y2, Y0
	VPCMPEQB     Y1, Y2, Y1
	VPOR         Y1, Y0, Y0
	VPMOVMSKB    Y0, AX
	MOVL         AX, mask+24(FP)
	MOVQ         $0x00000020, AX
	MOVQ         AX, processed+32(FP)
	VZEROUPPER
	RET

line_mask_done:
	XORL AX, AX
	MOVL AX, mask+24(FP)
	XORQ AX, AX
	MOVQ AX, processed+32(FP)
	VZEROUPPER
	RET

// func leadingSpacesAVX2Asm(data []byte) (count int, processed int)
// Requires: AVX, AVX2, BMI, SSE2
TEXT ·leadingSpacesAVX2Asm(SB), NOSPLIT, $0-40
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	CMPQ         CX, $0x00000020
	JB           spaces_done
	MOVL         $0x00000020, DX
	MOVD         DX, X0
	VPBROADCASTB X0, Y0
	XORQ         DX, DX
	SUBQ         $0x00000020, CX

spaces_loop:
	CMPQ      DX, CX
	JA        spaces_done
	VMOVDQU   (AX)(DX*1), Y1
	VPCMPEQB  Y0, Y1, Y1
	VPMOVMSKB Y1, BX
	NOTL      BX
	TESTL     BX, BX
	JNZ       spaces_found
	ADDQ      $0x00000020, DX
	JMP       spaces_loop

spaces_found:
	TZCNTL BX, AX
	MOVQ   DX, CX
	ADDQ   AX, CX
	MOVQ   CX, count+24(FP)
	ADDQ   $0x00000020, DX
	MOVQ   DX, processed+32(FP)
	VZEROUPPER
	RET

spaces_done:
	MOVQ DX, count+24(FP)
	MOVQ DX, processed+32(FP)
	VZEROUPPER
	RET
