// Code generated by command: go run classify.go -out ./internal/simd/asm_classify_amd64.s. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func indexEscapeOrControlAVX2Asm(data []byte) (index int, processed int)
// Requires: AVX, AVX2, BMI, SSE2
TEXT ·indexEscapeOrControlAVX2Asm(SB), NOSPLIT, $0-40
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	MOVL         $0x00000080, DX
	MOVD         DX, X0
	VPBROADCASTB X0, Y0
	MOVL         $0x000000a0, DX
	MOVD         DX, X1
	VPBROADCASTB X1, Y1
	MOVL         $0x0000005c, DX
	MOVD         DX, X2
	VPBROADCASTB X2, Y2
	XORQ         DX, DX
	SUBQ         $0x00000020, CX

escape_loop_start:
	CMPQ     DX, CX
	JA       escape_done
	VMOVDQU  (AX)(DX*1), Y3
	VPXOR    Y0, Y3, Y4
	VPCMPGTB Y4, Y1, Y4
	VPCMPEQB Y2, Y3, Y3
	VPOR     Y4, Y3, Y3
	VPTEST   Y3, Y3
	JNZ      escape_found
	ADDQ     $0x00000020, DX
	JMP      escape_loop_start

escape_found:
	VPMOVMSKB Y3, AX
	TZCNTL    AX, AX
	MOVQ      DX, CX
	ADDQ      AX, CX
	MOVQ      CX, index+24(FP)
	ADDQ      $0x00000020, DX
	MOVQ      DX, processed+32(FP)
	VZEROUPPER
	RET

escape_done:
	MOVQ $-1, AX
	MOVQ AX, index+24(FP)
	MOVQ DX, processed+32(FP)
	VZEROUPPER
	RET

// func indexSpecialOrControlAVX2Asm(data []byte, delim byte) (index int, processed int)
// Requires: AVX, AVX2, BMI, SSE2
TEXT ·indexSpecialOrControlAVX2Asm(SB), NOSPLIT, $0-48
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	MOVB         delim+24(FP), DL
	MOVL         $0x0000000f, BX
	MOVD         BX, X0
	VPBROADCASTB X0, Y0
	MOVQ         $0x1000080004020101, BX
	MOVQ         BX, X1
	VINSERTI128  $0x01, X1, Y1, Y1
	MOVQ         $0x0101010101030101, BX
	MOVQ         $0x0101190919050101, SI
	MOVQ         BX, X2
	MOVQ         SI, X3
	VPUNPCKLQDQ  X3, X2, X2
	VINSERTI128  $0x01, X2, Y2, Y2
	MOVBQZX      DL, BX
	MOVD         BX, X3
	VPBROADCASTB X3, Y3
	XORQ         BX, BX
	SUBQ         $0x00000020, CX
	CMPB         DL, $0x00
	JE           special_loop_nodelim

special_loop_delim:
	CMPQ     BX, CX
	JA       special_done
	VMOVDQU  (AX)(BX*1), Y4
	VPAND    Y0, Y4, Y5
	VPSRLW   $0x04, Y4, Y6
	VPAND    Y0, Y6, Y6
	VPSHUFB  Y5, Y2, Y5
	VPSHUFB  Y6, Y1, Y6
	VPAND    Y5, Y6, Y5
	VPCMPEQB Y3, Y4, Y4
	VPOR     Y4, Y5, Y5
	VPTEST   Y5, Y5
	JNZ      special_found_delim
	ADDQ     $0x00000020, BX
	JMP      special_loop_delim

special_found_delim:
	VPXOR     Y0, Y0, Y0
	VPCMPEQB  Y0, Y5, Y0
	VPMOVMSKB Y0, AX
	NOTL      AX
	TZCNTL    AX, AX
	MOVQ      BX, CX
	ADDQ      AX, CX
	MOVQ      CX, index+32(FP)
	ADDQ      $0x00000020, BX
	MOVQ      BX, processed+40(FP)
	VZEROUPPER
	RET

special_loop_nodelim:
	CMPQ    BX, CX
	JA      special_done
	VMOVDQU (AX)(BX*1), Y3
	VPAND   Y0, Y3, Y4
	VPSRLW  $0x04, Y3, Y3
	VPAND   Y0, Y3, Y3
	VPSHUFB Y4, Y2, Y4
	VPSHUFB Y3, Y1, Y3
	VPAND   Y4, Y3, Y3
	VPTEST  Y3, Y3
	JNZ     special_found_nodelim
	ADDQ    $0x00000020, BX
	JMP     special_loop_nodelim

special_found_nodelim:
	VPXOR     Y0, Y0, Y0
	VPCMPEQB  Y0, Y3, Y0
	VPMOVMSKB Y0, AX
	NOTL      AX
	TZCNTL    AX, AX
	MOVQ      BX, CX
	ADDQ      AX, CX
	MOVQ      CX, index+32(FP)
	ADDQ      $0x00000020, BX
	MOVQ      BX, processed+40(FP)
	VZEROUPPER
	RET

special_done:
	MOVQ $-1, AX
	MOVQ AX, index+32(FP)
	MOVQ BX, processed+40(FP)
	VZEROUPPER
	RET
