// Code generated by command: go run delim_quote.go -out ./internal/simd/asm_amd64.s. DO NOT EDIT.

//go:build amd64 && !purego

#include "textflag.h"

// func findDelimsAVX2Asm(data []byte, delim byte, dst []int, inQuotesIn bool) (n int, inQuotesOut bool, processed int)
// Requires: AVX, AVX2, BMI, SSE2
TEXT ·findDelimsAVX2Asm(SB), NOSPLIT, $0-88
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	MOVB         delim+24(FP), DL
	MOVBQZX      DL, DX
	MOVD         DX, X0
	VPBROADCASTB X0, Y0
	MOVL         $0x00000022, DX
	MOVD         DX, X1
	VPBROADCASTB X1, Y1
	MOVL         $0x0000005c, DX
	MOVD         DX, X2
	VPBROADCASTB X2, Y2
	MOVQ         dst_base+32(FP), DX
	MOVQ         dst_len+40(FP), BX
	MOVQ         dst_cap+48(FP), SI
	MOVB         inQuotesIn+56(FP), DI
	MOVBQZX      DI, DI
	NEGL         DI
	XORQ         R8, R8
	SUBQ         $0x00000020, CX

find_loop_start:
	CMPQ      R8, CX
	JA        find_done
	VMOVDQU   (AX)(R8*1), Y3
	VPCMPEQB  Y2, Y3, Y4
	VPMOVMSKB Y4, R9
	TESTL     R9, R9
	JNZ       find_done
	VPCMPEQB  Y0, Y3, Y4
	VPCMPEQB  Y1, Y3, Y3
	VPMOVMSKB Y3, R9
	MOVL      R9, R10
	SHLL      $0x01, R10
	XORL      R10, R9
	MOVL      R9, R10
	SHLL      $0x02, R10
	XORL      R10, R9
	MOVL      R9, R10
	SHLL      $0x04, R10
	XORL      R10, R9
	MOVL      R9, R10
	SHLL      $0x08, R10
	XORL      R10, R9
	MOVL      R9, R10
	SHLL      $0x10, R10
	XORL      R10, R9
	XORL      DI, R9
	MOVL      R9, DI
	SARL      $0x1f, DI
	VPMOVMSKB Y4, R10
	NOTL      R9
	ANDL      R10, R9

find_extract:
	TESTL  R9, R9
	JZ     find_next_stride
	CMPQ   BX, SI
	JAE    find_done
	TZCNTL R9, R10
	LEAQ   (R8)(R10*1), R10
	MOVQ   R10, (DX)(BX*8)
	INCQ   BX
	BLSRL  R9, R9
	JMP    find_extract

find_next_stride:
	ADDQ $0x00000020, R8
	JMP  find_loop_start

find_done:
	VZEROUPPER
	MOVQ  BX, n+64(FP)
	TESTL DI, DI
	SETNE AL
	MOVB  AL, inQuotesOut+72(FP)
	MOVQ  R8, processed+80(FP)
	RET

// func countDelimsAVX2Asm(data []byte, delim byte, inQuotesIn bool) (count int, inQuotesOut bool, processed int)
// Requires: AVX, AVX2, POPCNT, SSE2
TEXT ·countDelimsAVX2Asm(SB), NOSPLIT, $0-56
	MOVQ         data_base+0(FP), AX
	MOVQ         data_len+8(FP), CX
	MOVB         delim+24(FP), DL
	MOVBQZX      DL, DX
	MOVD         DX, X0
	VPBROADCASTB X0, Y0
	MOVL         $0x00000022, DX
	MOVD         DX, X1
	VPBROADCASTB X1, Y1
	MOVL         $0x0000005c, DX
	MOVD         DX, X2
	VPBROADCASTB X2, Y2
	MOVB         inQuotesIn+25(FP), DL
	MOVBQZX      DL, DX
	NEGL         DX
	XORQ         BX, BX
	XORQ         SI, SI
	SUBQ         $0x00000020, CX

count_loop_start:
	CMPQ      SI, CX
	JA        count_done
	VMOVDQU   (AX)(SI*1), Y3
	VPCMPEQB  Y2, Y3, Y4
	VPMOVMSKB Y4, DI
	TESTL     DI, DI
	JNZ       count_done
	VPCMPEQB  Y0, Y3, Y4
	VPCMPEQB  Y1, Y3, Y3
	VPMOVMSKB Y3, DI
	MOVL      DI, R8
	SHLL      $0x01, R8
	XORL      R8, DI
	MOVL      DI, R8
	SHLL      $0x02, R8
	XORL      R8, DI
	MOVL      DI, R8
	SHLL      $0x04, R8
	XORL      R8, DI
	MOVL      DI, R8
	SHLL      $0x08, R8
	XORL      R8, DI
	MOVL      DI, R8
	SHLL      $0x10, R8
	XORL      R8, DI
	XORL      DX, DI
	MOVL      DI, DX
	SARL      $0x1f, DX
	VPMOVMSKB Y4, R8
	NOTL      DI
	ANDL      R8, DI
	POPCNTL   DI, DI
	ADDQ      DI, BX
	ADDQ      $0x00000020, SI
	JMP       count_loop_start

count_done:
	VZEROUPPER
	MOVQ  BX, count+32(FP)
	TESTL DX, DX
	SETNE AL
	MOVB  AL, inQuotesOut+40(FP)
	MOVQ  SI, processed+48(FP)
	RET
