package differential_test

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"testing"

	toon "github.com/toon-format/toon-go"
)

type corpusCase struct {
	Name      string          `json:"name"`
	Input     json.RawMessage `json:"input"`
	TOON      string          `json:"toon"`
	Delimiter string          `json:"delimiter"`
}

// TestReferenceCorpus compares the Go canonical output with artifacts
// generated by @toon-format/toon v4.1.1. The artifacts are committed so the
// normal Go test graph stays offline and has no JavaScript dependency.
func TestReferenceCorpus(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("corpus.json"))
	if err != nil {
		t.Fatal(err)
	}
	var corpus []corpusCase
	if err := json.Unmarshal(data, &corpus); err != nil {
		t.Fatal(err)
	}
	for _, tc := range corpus {
		t.Run(tc.Name, func(t *testing.T) {
			var input any
			if err := json.Unmarshal(tc.Input, &input); err != nil {
				t.Fatal(err)
			}
			var opts []toon.EncoderOption
			if tc.Delimiter == "|" {
				opts = append(opts, toon.WithDelimiter(toon.DelimiterPipe))
			} else if tc.Delimiter == "\t" {
				opts = append(opts, toon.WithDelimiter(toon.DelimiterTab))
			}
			got, err := toon.MarshalString(input, opts...)
			if err != nil {
				t.Fatalf("MarshalString: %v", err)
			}
			if got != tc.TOON {
				t.Fatalf("reference mismatch\ngot:\n%s\nwant:\n%s", got, tc.TOON)
			}
			decoded, err := toon.DecodeString(tc.TOON)
			if err != nil {
				t.Fatalf("DecodeString reference output: %v", err)
			}
			if !reflect.DeepEqual(decoded, input) {
				t.Fatalf("cross-decode mismatch\ngot: %#v\nwant: %#v", decoded, input)
			}
		})
	}
}
